name: "PR Labeler"
on:
  - pull_request_target

jobs:
  triage:
    permisions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
