name: Test circuits

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths:
      - "packages/circuits/**/*.circom"
      - "packages/circuits/**/*.ts"
  pull_request:
    types: [opened, synchronize]
    path:
      - "packages/circuits/**/*.circom"
      - "packages/circuits/**/*.ts"

jobs:
  contracts-test-suite:
    runs-on: ubuntu-latest

    env:
      FORCE_COLOR: true
      REPORT_GAS: true

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v3.1.0
        with:
          node-version: "16"

      - run: yarn workspace @zk-game/circuits install
      - run: yarn workspace @zk-game/circuits test
