name: Test contracts (foundry)

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths:
      - "src/circuits/**/*.circom"
      - "test/circuits/**/*.ts"
  pull_request:
    types: [opened, synchronize]
    path:
      - "src/circuits/**/*.circom"
      - "test/circuits/**/*.ts"

jobs:
  foundry-test-suite:
    runs-on: ubuntu-latest

    env:
      FORCE_COLOR: true
      REPORT_GAS: true

    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - run: yarn install --immutable
      - run: yarn test:contracts
